### PR TITLE
fixes: remove unused gRPC bits, stop forcing gRPC to 1.38.0.

### PR DESCRIPTION
**Pull request by klihub**
- resmgr,log,net: ditch unused gRPC helper bits
- go.{mod,sum}: stop forcing gRPC to version 1.38.0

This should prevent getting [flagged]( https://artifacthub.io/packages/helm/nri-plugins/nri-resource-policy-balloons?modal=security-report) with a high-severity gRPC vulnerability.

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
LGTM

**Review by fmuyassarov — APPROVED** [review]
LGTM

**Comment by fmuyassarov** [comment]
@klihub I see that `IsListeningSocket()` is kept here. But there is no caller for it. Should we keep it or remove too?

**Comment by klihub** [comment]
> @klihub I see that `IsListeningSocket()` is kept here. But there is no caller for it. Should we keep it or remove too?

I guess it could be removed, too. I decided initially not to remove in this PR, as this is about ditching unused gRPC-related bits and updating our gRPC dep.

**Pull request merged**
