### PR TITLE
Helm improvments

### PR DESCRIPTION
**Pull request by fmuyassarov**
This PR adds a GitHub action for linting Helm charts on pull requests and fixes minor issue with namespaces in the Helm chart installation guide.

Helm linter is basically validating helm chart values in a chart's values.yaml file with [JSON schemas](https://json-schema.org/).

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Here is the GitHub action result of the first linter run: https://github.com/containers/nri-plugins/actions/runs/5377726551/jobs/9756576779?pr=85

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by klihub** [comment]
@fmuyassarov The PR as such looks fine to me, but my related question is: shouldn't/couldn't we please have a helm chart for the template policy as well ? One of the main point of the template policy is that it serves as a `code monkey see, code monkey do` template for folks to bootstrap developing their own custom policy, without having to first understand all the bits and pieces in this repo to get things right. IMO, this should also cover anything related to deployment, including helm charts (and event documentation).

**Review by klihub — APPROVED** [review]
This LGTM, but please @jukkar, @fmuyassarov take a look at a my related question.

**Comment by fmuyassarov** [comment]
> @fmuyassarov The PR as such looks fine to me. That said, I have a tangentially related question now that I look at the changes: Shouldn't/couldn't we, please, have a helm chart for the template policy as well ?
> 
> One of the main points of the template policy is that it serves as a `code monkey see, code monkey do`-template for folks to bootstrap developing their own custom policy. This should happen without first having to understand all the bits and pieces in this repo to get things right/up and running. And IMO, this should cover anything related to the policy , including deployment, helm charts, and even documentation.
> 
> @marquiz, @jukkar WDYT ?

I can definitely add chart for the template policy + kustomize installation. Would you like that to happen on this PR or shall I send a seperate PR for that (personally I prefer to have separate PR)?

**Comment by jukkar** [comment]
> Shouldn't/couldn't we, please, have a helm chart for the template policy as well ?

Makes sense, +1 to this.

**Review by jukkar — APPROVED** [review]
LGTM, I am ok if the template changes are in separate pr.

**Comment by klihub** [comment]
Yes, I also think separate PR is fine.

**Pull request merged**
