### PR TITLE
github-action: update charts path to include memtierd and memory-qos

### PR DESCRIPTION
**Pull request by fmuyassarov**

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
LGTM

**Comment by fmuyassarov** [comment]
Requires https://github.com/containers/nri-plugins/pull/127 and https://github.com/containers/nri-plugins/pull/128.

**Review by marquiz — APPROVED** [review]
LGTM

**Comment by marquiz** [comment]
Needs rebase

**Comment by fmuyassarov** [comment]
> Needs rebase

Done

**Review by marquiz — APPROVED** [review]

**Pull request merged**
