### PR TITLE
helm: add an option to set tolerations

### PR DESCRIPTION
**Pull request by fmuyassarov**
In some clusters, some of the Nodes might have taints which may avoid NRI plugins DaemonSet Pods not to get scheduled on those Nodes. Having an option to pass custom tolerations to plugins DaemonSet object would help to ensure that Pods get scheduled on all the desired Nodes.

### CODE REVIEW

**Review by klihub — APPROVED** [review]
LGTM

**Comment by kad** [comment]
Should we have example of most useful tolerations in the doc?

**Review by klihub — CHANGES_REQUESTED** [review]
Needs a rebase and resolving conflicts. And an example as requested by @kad would also be good.

**Comment by klihub** [comment]
@fmuyassarov Could you rebase this on latest main HEAD and resolve the conflicts ? We could get it then merged.

**Comment by fmuyassarov** [comment]
@kad @klihub PTAL, I have now updated the PR. Thanks.

**Review by klihub — APPROVED** [review]

**Comment by klihub** [comment]
@kad @askervin PTAL

**Review by askervin — APPROVED** [review]
Nice, @fmuyassarov! LGTM.

**Pull request merged**
