### PR TITLE
cpuallocator, plugins: handle priority as an option.

### PR DESCRIPTION
**Pull request by klihub**
Turn priority of CPUs to allocate/release into an opaque option passed to `cpuallocator.{Allocate,Release}Cpus()`. This should make it much easier to add new options to the allocator in the future.

### CODE REVIEW

**Review by askervin — APPROVED** [review]
LGTM

**Review by marquiz — APPROVED** [review]
LGTM

**Review by askervin — APPROVED** [review]
LGTM

**Comment by askervin** [comment]
@klihub, is this ready for merge, or are you planning to add some more With... options?

**Comment by klihub** [comment]
Yes, I have already one (WithAllocFlags()) on top of this, but I was planning to file that as a separate PR.

**Comment by klihub** [comment]
> @klihub, is this ready for merge, or are you planning to add some more With... options?

@askervin Yes, I have already two in the pipeline stacked on this but I was planning to file those separately and this one just to pave the way for those. One a straightforward `WithAllocFlags()` to allow overriding the default allocation flags, and another which introduces a new `PreferPartialSharedGroups` alloc flag to indicate preference to use partially allocated groups instead of always unconditionally slicing up idle ones.

**Pull request merged**
