### PR TITLE
cleanup: nuke unused scripts, Makefile bits and defunct functionality.

### PR DESCRIPTION
**Pull request by klihub**
This patch set nukes
- unused docker-build-image script and a few unused Makefile variables
- defunct page-migration controller/controls (obsoleted by memtierd)
- defunct memory controller/controls (related kernel control knobs never upstreamed)
- defunct introspection API (visualization already removed earlier)
- defunct metrics-based rebalancing

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Love it ❤️
LGTM

**Comment by kad** [comment]
I'm worried about rebalance infra of code. Probably need to make a backlog item to redesign it to work as expected in NRI scope.

**Comment by marquiz** [comment]
> I'm worried about rebalance infra of code. Probably need to make a backlog item to redesign it to work as expected in NRI scope.

I think it's best to nuke the unused/untested code. Create a new GitHub issue about enabling it we want it back.

**Review by fmuyassarov — COMMENTED** [review]
LGTM

**Pull request merged**
