### PR TITLE
docs: fix md style

### PR DESCRIPTION
**Pull request by marquiz**
Fix the following issues raised by markdownlint:

- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md004---unordered-list-style
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md005---inconsistent-indentation-for-list-items-at-the-same-level
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md006---consider-starting-bulleted-lists-at-the-beginning-of-the-line
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md009---trailing-spaces
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md010---hard-tabs
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md012---multiple-consecutive-blank-lines
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013---line-length
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md032---lists-should-be-surrounded-by-blank-lines
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md040---fenced-code-blocks-should-have-a-language-specified

Inspired by #169. If you like this idea we could enable [markdownlint](https://github.com/markdownlint/markdownlint) in the CI.

### CODE REVIEW

**Comment by klihub** [comment]
@marquiz I think this could be a good idea.

What would be the best way to hook this in, as this is not a github workflow ? Should we run it as part of the containerized doc build ? That would automatically buy us a local check for free.

**Comment by klihub** [comment]
> @marquiz I think this could be a good idea.
> 
> What would be the best way to hook this in, as this is not a github workflow ? Should we run it as part of the containerized doc build ? That would automatically buy us a local check for free.

Okay, actually there is a github action for it...

**Comment by marquiz** [comment]
> Okay, actually there is a github action for it...

That or then just have a shell script action

**Comment by marquiz** [comment]
Rebased, plus two small whitespaces fixes. Ready for review

**Review by fmuyassarov — APPROVED** [review]
Would be nice to have the markdownlinter enabled as precheck at least for docs directory related PRs.
LGTM

**Review by klihub — APPROVED** [review]

**Pull request merged**
