### PR TITLE
github: Add document publishing action

### PR DESCRIPTION
**Pull request by jukkar**
Make sure document publishing works for main and release branches.

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Looks good to me.

@jukkar Have you tried/verified this e.g. in your personal repo?

**Comment by klihub** [comment]
@jukkar @marquiz I tried it in my personal repo just now. Weird, it fails with a permission denied error/403 when it tries to push to the `gh-pages` branch.

**Comment by marquiz** [comment]
> I tried it in my personal repo just now. Weird, it fails with a permission denied error/403 when it tries to push to the `gh-pages` branch.

Hmm 🧐 Have you enabled gh-pages in the repo settings? Maybe you first need to create the branch manually (or have you already done that?)

**Comment by marquiz** [comment]
Ach, @klihub you probably need to modify the actions/workflow permissions in the repo settings

**Comment by klihub** [comment]
> > I tried it in my personal repo just now. Weird, it fails with a permission denied error/403 when it tries to push to the `gh-pages` branch.
> 
> Hmm monocle_face Have you enabled gh-pages in the repo settings? Maybe you first need to create the branch manually (or have you already done that?)

Yes, I enabled. And yes I first created the branch, so that shouldn't be it.

**Comment by klihub** [comment]
> Ach, @klihub you probably need to modify the actions/workflow permissions in the repo settings
> 
> EDIT: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

Okay, I have to check that. Maybe that's the problem.

**Comment by klihub** [comment]
@marquiz Thanks ! After granting permissions now it works.

**Comment by jukkar** [comment]
Changed the "master" -> "main" in `update-gh-pages.sh` script.

**Review by klihub — APPROVED** [review]

**Comment by marquiz** [comment]
Cool, script seemed to work! Now somebody needs to enable gh-pages for the repo

**Pull request merged**
