### PR TITLE
agent: fix the (short) import path for NRT api

### PR DESCRIPTION
**Pull request by fmuyassarov**

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
LGTM

**Review by klihub — APPROVED** [review]
Out of curiosity: why is this a 'fix' ?

**Comment by marquiz** [comment]
> Out of curiosity: why is this a 'fix' ?

looks like unifying the import name

**Comment by fmuyassarov** [comment]
Yea probably I should be careful with the wording here. This is not a fix indeed and just a cosmetic change to follow the same pattern.

**Pull request merged**
