### PR TITLE
deps: bump NRT dependencies to v0.1.2.

### PR DESCRIPTION
**Pull request by fmuyassarov**
Bump NRT api to the latest release v0.1.2

### CODE REVIEW

**Comment by klihub** [comment]
LGTM.

Is there any new data wrt. previous versions we should consider providing ?

**Comment by fmuyassarov** [comment]
> LGTM.
> 
> Is there any new data wrt. previous versions we should consider providing ?

I believe (according to the PRs that went in) no.

**Review by askervin — APPROVED** [review]
LGTM

**Review by marquiz — APPROVED** [review]
LGTM

**Pull request merged**
